### 矩阵计算库

In [1]:
import numpy as np

In [3]:
vector = np.array([5,2,6,8,1]) # 一维矩阵（一个中括号）
vector2 = np.array([[3,6,8,3],[8,4,2,8]])  # 二维矩阵

In [4]:
vector

array([5, 2, 6, 8, 1])

In [5]:
vector2

array([[3, 6, 8, 3],
       [8, 4, 2, 8]])

In [6]:
vector.shape

(5,)

In [7]:
vector2.shape

(2, 4)

### 基础结构

In [8]:
num = np.array([1,2,3,4])
num2 = np.array([1,2,3,'4'])
# 构造np.array时，所有数据必须是相同结构

In [9]:
print(num)
num.dtype   #  查看类型

[1 2 3 4]


dtype('int32')

In [10]:
print(num2)
num2.dtype

['1' '2' '3' '4']


dtype('<U11')

### 数据索引

In [11]:
num3 = np.array([[2,6,8,3,],[6,8,3,22],[76,432,75,23]])
print(num3)

[[  2   6   8   3]
 [  6   8   3  22]
 [ 76 432  75  23]]


In [12]:
print(num3[2,3])  # 索引第三行第四列，索引方式与列表索引相同
print(num3[0,2])

23
8


### 切片

In [13]:
num4 = np.array([6,3,6,2,7,2,65])
print(num4[0:3])  # 左闭右开

[6 3 6]


##### 取矩阵中一列的所有值

In [14]:
# 取矩阵中一列的所有值， ： (冒号)表示所有，所有的行
num3 = np.array([[2,6,8,3,],
                 [6,8,3,22],
                 [7,4,75,23]])
print(num3[:,1])   

[6 8 4]


##### 取矩阵中两列列的所有值

In [15]:
num3 = np.array([[2,6,8,3,],
                 [6,8,3,22],
                 [7,4,75,23]])
print(num3[:,0:2])  # 一二维都用切片索引

[[2 6]
 [6 8]
 [7 4]]


### 判断

In [16]:
dds = np.array([542,5532,78,2,7])
dds == 78  # 会对其中的每个元素都进行判断操作

array([False, False,  True, False, False])

In [17]:
num3 = np.array([[2,6,8,3,],
                 [6,8,3,22],
                 [7,4,75,23]])
num3 == 3

array([[False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

#### 布尔值索引

In [18]:
dds = np.array([542,5532,78,2,7])
adc = (dds == 2)
print(adc)

[False False False  True False]


In [19]:
print(dds[adc])   # 把为True的值打印出来

[2]


In [3]:
num3 = np.array([[2,6,8,3,],
                 [6,8,3,22],
                 [7,4,75,23]])

a = num3[:,2]==75
print(a)
print(num3[a,:])

[False False  True]
[[ 7  4 75 23]]


#### 与或操作

In [21]:
# 与操作（一个数不可能等于两个值，所以一下示例都是False）
yy = np.array([5,10,15,23])

print((yy==5)&(yy==10))

[False False False False]


In [22]:
# 或操作 (满足其中一个条件就打印)
print((yy==5)|(yy==10))

[ True  True False False]


### 值类型转换

In [23]:
fg = np.array(['1','2','3'])
print(fg.dtype)
print(fg)

<U1
['1' '2' '3']


In [24]:
fg = fg.astype(int)   # 转换
print(fg.dtype)
print(fg)

int32
[1 2 3]


### 进行求极值操作

In [25]:
fg = np.array([1,2,3])
print(fg.min())  # 最小值
print(fg.max())  # 最大值

1
3


### 其他

In [26]:
print(help(np.array))     # 查看官方帮助文档

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

### 求和（按行或按列）

In [27]:
# 按行求和
hj = np.array([
                [1,2,4],
                [5,6,7],
                [8,9,0]
              ])
hj.sum(axis=1)   # 指定维度求和 ，按行求和

array([ 7, 18, 17])

In [28]:
# 按列求和
hj.sum(axis=0)

array([14, 17, 11])

### Numpy 常用函数

In [29]:
import numpy as np
a = np.array([range(15)])  # np.arange(15)
a = a.reshape(3, 5)   # 转换为矩阵形式 
print(a)
print('\n_____等同写法_____')
print(np.array([range(15)]).reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

_____等同写法_____
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
print(a.shape)    # 查看行和列
print(a.shape[1])  # 索引 列 值

(3, 5)
5


In [31]:
a.ndim     # 查看维度,有几个中括号就是几维

2

In [32]:
a.dtype   # 查看矩阵类型

dtype('int32')

In [33]:
a.size  # 查看矩阵元素个数

15

### 初始化矩阵

In [34]:
w = np.zeros((3,3,4))  # 构造一个3行4列的零矩阵  
w

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
w.ndim  # 查看维度

3

In [36]:
w.shape  # 查看矩阵行列数

(3, 3, 4)

In [37]:
f = np.ones((4,3,4), dtype=np.int32)  # 构造一个类型为int型的零矩阵
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [38]:
f.ndim  # 查看维度

3

In [39]:
# print(help(np.ones))

### np.arange

In [40]:
# 从10开始每5打印一个，与Python中的range用法相同
np.arange(10,30,5)

array([10, 15, 20, 25])

In [41]:
np.arange(10).reshape(2,5)  # 0到10构造一个2行5列的二维矩阵矩阵

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### np.random.random()

In [42]:
# 随机数函数
np.random.random((2,3))

array([[0.14925791, 0.26145368, 0.2322366 ],
       [0.1990482 , 0.73049798, 0.27848789]])

### 运算·

In [43]:
r = np.array([10,20,30,40])
e = np.arange(4)
c = r-e

In [44]:
c  # 对应位置相减

array([10, 19, 28, 37])

### 矩阵的常用操作

In [45]:
t = np.zeros((3,3,4))

In [46]:
t

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
# 合
t.hstack  # 横
t.vstack  # 竖

# 分
t.hsplit


AttributeError: 'numpy.ndarray' object has no attribute 'hstack'

# 梵蒂冈